site_name: Waffle Documentation
site_url: https://docs.wafflesoc2.com
site_description: Simple, SOC 2-compliant AWS infrastructure for containerized backends
site_author: Waffle Team
repo_url: https://github.com/WaffleCodeApp/waffle-templates
repo_name: WaffleCodeApp/waffle-templates

theme:
  name: material
  palette:
    primary: amber  # Waffle-themed warm color (April 10, 2025)
    accent: deep orange
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - content.tabs
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Reference: reference.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
